version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jarvis-api
    env_file:
      - .env
    environment:
      LOG_LEVEL: INFO
    ports:
      - "8000:8000"
    volumes:
      - model_cache:/root/.cache
volumes:
  model_cache: